export enum UserRole {
  ADMIN = "ADMIN",
  SALES = "SALES",
  SANCTION = "SANCTION",
  DISBURSEMENT = "DISBURSEMENT",
  COLLECTION = "COLLECTION",
  BORROWER = "BORROWER",
}

export enum LoanStatus {
  APPLIED = "APPLIED",
  REJECTED = "REJECTED",
  SANCTIONED = "SANCTIONED",
  DISBURSED = "DISBURSED",
  CLOSED = "CLOSED",
}